method: random
metric:
  goal: maximize
  name: best_validation_log_prob
parameters:
  batch:
    distribution: q_log_uniform_values
    max: 256
    min: 16
    q: 8
  model:
    values:
      - maf
  lr:
    distribution: q_log_uniform_values
    max: 1e-3
    min: 1e-5
    q: 1e-05
  nhidden:
    distribution: q_log_uniform_values
    max: 128
    min: 32
    q: 8
  ntransforms:
    distribution: int_uniform
    max: 10
    min: 3
  nblocks:
    distribution: int_uniform
    max: 5
    min: 2